# Task1:

In [2]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = a[2:5]
print("Slice:", b)

Slice: [30 40 50]


In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
scnd = matrix[:, 1]
print("Second Column:", scnd)

Second Column: [2 5 8]


In [4]:
matrix = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
sub = matrix[1:3, [0, 2]]
print("Sub:")
print(sub)

Sub:
[[21 23]
 [31 33]]


In [5]:
tensor = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]],
                   [[21, 22, 23, 24, 25], [26, 27, 28, 29, 30], [31, 32, 33, 34, 35], [36, 37, 38, 39, 40]],
                   [[41, 42, 43, 44, 45], [46, 47, 48, 49, 50], [51, 52, 53, 54, 55], [56, 57, 58, 59, 60]]])
slicing = tensor[1]
print("Sliced:")
print(slicing)

Sliced:
[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [6]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
even = data[data % 2 == 0]
print("Even Numbers :", even)

Even Numbers : [2 4 6 8]


# Task2:

In [7]:
import numpy as np

image = np.array([[10, 20, 30, 40, 50],
                  [60, 70, 80, 90, 100],
                  [110, 120, 130, 140, 150],
                  [160, 170, 180, 190, 200],
                  [210, 220, 230, 240, 250]])

R = image[1:4, 1:4]
print(R)


[[ 70  80  90]
 [120 130 140]
 [170 180 190]]


In [8]:
temperature= np.array([[75.2, 78.3, 81.5, 79.0, 82.1],
                            [71.6, 73.8, 76.2, 72.4, 77.5],
                            [69.3, 70.7, 73.2, 71.1, 74.8],
                            [74.8, 76.2, 78.4, 76.0, 80.5]])

temp = temperature[2, 1:4]
print(temp)


[70.7 73.2 71.1]


In [9]:
stock = np.array([[50.0, 51.2, 49.5, 48.9, 50.3],
                      [62.1, 60.5, 63.2, 59.7, 61.0],
                      [90.5, 88.7, 91.2, 92.0, 89.5]])

stock2 = stock[1, 0:3]
print(stock2)

[62.1 60.5 63.2]


In [10]:
scores = np.array([[85, 92, 78],
                          [90, 88, 76],
                          [78, 85, 92],
                          [95, 91, 89]])

student3 = scores[2, :]

performance = np.mean(student3)
print(student3)
print(performance)


[78 85 92]
85.0


# Task3:

In [12]:
import numpy as np

cube = np.array([[[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20]],
                 [[21, 22, 23, 24, 25],
                  [26, 27, 28, 29, 30],
                  [31, 32, 33, 34, 35],
                  [36, 37, 38, 39, 40]],
                 [[41, 42, 43, 44, 45],
                  [46, 47, 48, 49, 50],
                  [51, 52, 53, 54, 55],
                  [56, 57, 58, 59, 60]]])

element_1 = cube[2, 3, 4]
print(element_1)

array = cube[1]
print(array)
row = cube[1, 0]
print(row)
sub_matrix = cube[2, 1:3, 1:4]
print(sub_matrix)


60
[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]
[21 22 23 24 25]
[[47 48 49]
 [52 53 54]]


In [13]:
data_cube = np.array([[[10, 20, 30],
                       [40, 50, 60],
                       [70, 80, 90]],
                      [[110, 120, 130],
                       [140, 150, 160],
                       [170, 180, 190]],
                      [[210, 220, 230],
                       [240, 250, 260],
                       [270, 280, 290]],
                      [[310, 320, 330],
                       [340, 350, 360],
                       [370, 380, 390]]])

element_2 = data_cube[2, 1, 1]
print(element_2)

array = data_cube[3]
print(array)

column = data_cube[0, :, 2]
print(column)

sub = data_cube[2, 0:2, 1:3]
print(sub)


250
[[310 320 330]
 [340 350 360]
 [370 380 390]]
[30 60 90]
[[220 230]
 [250 260]]


In [14]:
color_cube = np.array([[[255, 0, 0],
                        [0, 255, 0],
                        [0, 0, 255]],
                       [[128, 128, 0],
                        [0, 128, 128],
                        [128, 0, 128]]])

rgb_value = color_cube[1, 1, 2]
print(rgb_value)

array = color_cube[0]
print(array)

green = color_cube[0, :, 1]
print(green)

sub = color_cube[0, 0:2, 1:3]
print(sub)


128
[[255   0   0]
 [  0 255   0]
 [  0   0 255]]
[  0 255   0]
[[  0   0]
 [255   0]]


# Task4:

In [15]:
import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

elements_greater = matrix[matrix > 8]
print(elements_greater)

divisible = matrix[matrix % 3 == 0]
print(divisible)


[ 9 10 11 12 13 14 15 16]
[ 3  6  9 12 15]


In [16]:
data_cube = np.array([[[10, 20, 30],
                       [40, 50, 60],
                       [70, 80, 90]],
                      [[110, 120, 130],
                       [140, 150, 160],
                       [170, 180, 190]],
                      [[210, 220, 230],
                       [240, 250, 260],
                       [270, 280, 290]],
                      [[310, 320, 330],
                       [340, 350, 360],
                       [370, 380, 390]]])

elements_greater = data_cube[data_cube > 100]
print(elements_greater)

divisible = data_cube[data_cube % 20 == 0]
print(divisible)

mask = (data_cube > 250) & (data_cube < 350)

masked_elements = data_cube[mask]
print(masked_elements)


[110 120 130 140 150 160 170 180 190 210 220 230 240 250 260 270 280 290
 310 320 330 340 350 360 370 380 390]
[ 20  40  60  80 120 140 160 180 220 240 260 280 320 340 360 380]
[260 270 280 290 310 320 330 340]
