In [2]:
arr = [27, 15, 8, 42, 5, 13, 36, 19, 10, 31]
arr.sort()
arr

[5, 8, 10, 13, 15, 19, 27, 31, 36, 42]

In [4]:
import numpy as np
a = np.random.randn(15)
a

array([-1.2666099 , -0.43213385,  0.24746069,  1.44333794, -0.23476354,
       -0.89354781,  0.70349801, -0.19559553,  0.49822382, -1.97075125,
       -0.43632775,  0.71025855,  0.1714224 ,  1.14244052,  0.35764937])

In [7]:
a.sort()
a

array([-1.97075125, -1.2666099 , -0.89354781, -0.43632775, -0.43213385,
       -0.23476354, -0.19559553,  0.1714224 ,  0.24746069,  0.35764937,
        0.49822382,  0.70349801,  0.71025855,  1.14244052,  1.44333794])

In [8]:
matrix = np.array([[14,29,5],[37,8,21],[10,46,18]])
matrix

array([[14, 29,  5],
       [37,  8, 21],
       [10, 46, 18]])

In [9]:
matrix.sort()
matrix

array([[ 5, 14, 29],
       [ 8, 21, 37],
       [10, 18, 46]])

In [15]:
a = np.random.randn(4,4)
a

array([[-0.65377385, -0.79475442,  1.68366043, -0.08249089],
       [-2.32066131,  0.57208985,  0.83619769,  1.07656499],
       [-0.81342375,  0.67163128,  0.34363129, -0.29075047],
       [-0.19885252,  0.02082002,  0.57955439,  0.87836795]])

In [16]:
a.sort(axis=0)
a

array([[-2.32066131, -0.79475442,  0.34363129, -0.29075047],
       [-0.81342375,  0.02082002,  0.57955439, -0.08249089],
       [-0.65377385,  0.57208985,  0.83619769,  0.87836795],
       [-0.19885252,  0.67163128,  1.68366043,  1.07656499]])

In [17]:
data = [57, 24, 10, 35, 48, 13, 29, 42, 5, 18]
data

[57, 24, 10, 35, 48, 13, 29, 42, 5, 18]

In [24]:
np.sort(data[:5])

array([10, 24, 35, 48, 57])

In [29]:
b = np.random.randint(0,10,21)
b

array([6, 4, 2, 2, 5, 7, 2, 5, 0, 9, 7, 4, 6, 1, 9, 4, 2, 6, 0, 0, 4])

In [33]:
c = np.sort(b)
c

array([0, 0, 0, 1, 2, 2, 2, 2, 4, 4, 4, 4, 5, 5, 6, 6, 6, 7, 7, 9, 9])

In [36]:
matrix = np.array([[43,19,7],[30,52,14],[8,36,27]])
matrix

array([[43, 19,  7],
       [30, 52, 14],
       [ 8, 36, 27]])

In [37]:
c = np.sort(matrix,axis=0)
c

array([[ 8, 19,  7],
       [30, 36, 14],
       [43, 52, 27]])

In [38]:
a = np.random.randn(5,5)
a

array([[ 0.06094086, -0.78812028,  0.78415831,  0.88584436,  0.22801634],
       [ 0.52364002,  0.09223447, -0.42495439, -1.82888081, -0.19362614],
       [ 1.12566418, -1.6176467 ,  0.74752666, -0.48830099, -1.01864111],
       [-1.19947159, -0.04123514,  0.28978905,  0.18979253,  1.04687341],
       [-0.05024884, -0.65820586, -1.75514581, -0.969268  , -0.01467607]])

In [39]:
c = np.sort(a)
c

array([[-0.78812028,  0.06094086,  0.22801634,  0.78415831,  0.88584436],
       [-1.82888081, -0.42495439, -0.19362614,  0.09223447,  0.52364002],
       [-1.6176467 , -1.01864111, -0.48830099,  0.74752666,  1.12566418],
       [-1.19947159, -0.04123514,  0.18979253,  0.28978905,  1.04687341],
       [-1.75514581, -0.969268  , -0.65820586, -0.05024884, -0.01467607]])

In [40]:
data = [23, 17, 41, 9, 32, 12, 5, 28, 14, 36]
data

[23, 17, 41, 9, 32, 12, 5, 28, 14, 36]

In [41]:
data.sort()

In [42]:
data

[5, 9, 12, 14, 17, 23, 28, 32, 36, 41]

In [44]:
d = np.random.randint(0,30,25)
d

array([16, 23, 25,  9, 12, 24,  1, 17, 29,  5, 17,  9, 29, 20, 10,  9,  7,
       27,  8, 16, 12, 29,  5, 20,  2])

In [45]:
c = np.sort(d)
c

array([ 1,  2,  5,  5,  7,  8,  9,  9,  9, 10, 12, 12, 16, 16, 17, 17, 20,
       20, 23, 24, 25, 27, 29, 29, 29])

# Task: 2

In [46]:
arr1 = [15, 7, 29, 12, 7, 42, 15, 29, 18, 5]
arr2 = [29, 5, 12, 8, 18, 42, 15, 7, 10, 23]
c = np.unique(arr1,arr2)
c

(array([ 5,  7, 12, 15, 18, 29, 42]),
 array([9, 1, 3, 0, 8, 2, 5], dtype=int64))

In [47]:
d = np.random.randint(0,30,20)
d

array([27, 20, 14, 28,  8,  4, 13,  1, 18, 14, 27, 26, 28, 24, 23, 11, 26,
       25,  0,  6])

In [48]:
c = np.unique(d)
c

array([ 0,  1,  4,  6,  8, 11, 13, 14, 18, 20, 23, 24, 25, 26, 27, 28])

In [49]:
arr3 = [12, 5, 18, 7, 29, 42]
arr4 = [7, 10, 23, 29]
c = np.intersect1d(arr3,arr4)
c

array([ 7, 29])

In [50]:
d = np.random.randint(0,30,15)
e = np.random.randint(0,30,15)
d,e

(array([29,  3, 12, 19, 14, 14,  1, 27, 19, 23,  5,  7, 29, 15, 21]),
 array([16, 14, 28,  9, 23,  7, 15, 11, 21, 29,  6, 12, 29, 18, 11]))

In [51]:
c = np.intersect1d(d,e)
c

array([ 7, 12, 14, 15, 21, 23, 29])

In [52]:
arr5 = [15, 7, 29, 12, 7, 42, 15, 29, 18, 5]
arr6 = [29, 5, 12, 8, 18, 42, 15, 7, 10, 23]
c = np.unique(arr5,arr6)
c

(array([ 5,  7, 12, 15, 18, 29, 42]),
 array([9, 1, 3, 0, 8, 2, 5], dtype=int64))

In [53]:
d = np.random.randint(0,30,25)
e = np.random.randint(0,30,25)
d,e

(array([17, 24, 14,  1, 24, 13, 22, 16, 10, 25, 21, 14,  1, 26, 25, 29,  6,
         7,  8, 19, 26,  0, 20,  3, 14]),
 array([15,  7,  9, 13,  3, 14, 14,  9, 24, 15, 25,  7,  3,  0, 28,  8,  9,
        18, 23, 15, 23,  4, 27,  8, 14]))

In [56]:
c = np.unique(d)
g = np.unique(e)
c,g

(array([ 0,  1,  3,  6,  7,  8, 10, 13, 14, 16, 17, 19, 20, 21, 22, 24, 25,
        26, 29]),
 array([ 0,  3,  4,  7,  8,  9, 13, 14, 15, 18, 23, 24, 25, 27, 28]))

In [57]:
arr7 = [15, 7, 29, 12, 7, 42, 15, 29, 18, 5]
arr8 = [29, 5, 12, 8, 18, 42, 15, 7, 10, 23]
c = np.union1d(arr7,arr8)
c

array([ 5,  7,  8, 10, 12, 15, 18, 23, 29, 42])

In [59]:
d = np.random.randint(0,30,30)
e = np.random.randint(0,30,30)
d,e
c = np.union1d(d,e)
c

array([ 0,  1,  2,  3,  4,  5,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       20, 21, 22, 23, 24, 25, 26, 27, 29])

In [60]:
arr9 = [15, 7, 29, 12, 7, 42, 15, 29, 18, 5]
arr10 = [29, 5, 12, 8, 18, 42, 15, 7, 10, 23]
np.unique(arr9)

array([ 5,  7, 12, 15, 18, 29, 42])

In [62]:
d = np.random.randint(0,30,35)
e = np.random.randint(0,30,35)
d,e
np.unique(d)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 14, 20, 22, 23,
       25, 26, 27, 28])

# Task: 3

In [2]:
import numpy as np
array1 = np.random.randint(1, 101, 15)
print(array1)

array2 = np.random.rand(4, 6)
print(array2)

array3 = np.random.randn(20)
print(array3)

matrix4 = np.random.randint(-50, 51, (3, 3))
print(matrix4)

array5 = np.random.uniform(0, 1, 25)
print(array5)

array6 = np.random.binomial(1, 0.5, (5, 5))
print(array6)

np.random.seed(42)
matrix7 = np.random.randint(0, 101, (3, 3))
print(matrix7)

rng = np.random.RandomState(123)
array8 = rng.randint(0, 101, (6, 4))
print(array8)


[50 26 76 41  2 19 77 23 89  4 40 90 56 97 44]
[[0.2261401  0.81405625 0.21202717 0.61436868 0.21235708 0.85254154]
 [0.08735531 0.37337513 0.50249802 0.12897678 0.76502146 0.87096821]
 [0.10303633 0.10341055 0.19551782 0.18350885 0.96451262 0.70405437]
 [0.16749664 0.30410807 0.85422218 0.56504877 0.08801334 0.37216312]]
[-0.10397509 -1.28897683  0.14446134  1.76637184  0.41383183 -0.02525954
  0.85842687 -0.61988389  0.54141603 -0.84135544 -0.74649503 -0.82693108
 -0.36303851  0.4470879   1.58403363 -0.55478492 -0.13604924 -2.88771522
  0.18960268  0.3513221 ]
[[  9 -36  12]
 [  5 -13  25]
 [  2  37 -22]]
[0.44681908 0.05928301 0.95469142 0.47753724 0.30336078 0.94193351
 0.06851691 0.25972789 0.06746764 0.37652595 0.86447265 0.20263916
 0.07329602 0.1895453  0.99245575 0.32856585 0.39886134 0.89615635
 0.03827998 0.02851922 0.37076346 0.97942519 0.14343933 0.69875046
 0.44144849]
[[1 1 1 1 0]
 [1 1 1 0 0]
 [1 1 0 1 0]
 [1 1 1 1 0]
 [1 0 0 0 0]]
[[51 92 14]
 [71 60 20]
 [82 86 74]]
[

# Task;4

In [3]:
arr1 = np.array([2, 4, 6, 8, 10, 12, 14, 16])
reshaped_arr1 = arr1.reshape(2, -1)
print("Reshaped Array 1:\n", reshaped_arr1)

random_array2 = np.random.randint(1, 101, 20)
reshaped_arr2 = random_array2.reshape(4, 5)
print("Original random array 2:", random_array2)
print("Reshaped Array 2:\n", reshaped_arr2)

arr3 = np.array([1, 3, 5, 7, 9, 11, 13, 15])
reshaped_arr3 = arr3.reshape(-1, 4)
print("Reshaped Array 3:\n", reshaped_arr3)

random_array4 = np.random.randint(1, 101, 30)
reshaped_arr4 = random_array4.reshape(3, 10)
print("Original random array 4:", random_array4)
print("Reshaped Array 4:\n", reshaped_arr4)

arr5 = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
reshaped_arr5 = arr5.reshape(5, -1)
print("Reshaped Array 5:\n", reshaped_arr5)

random_array6 = np.random.randint(1, 101, 25)
reshaped_arr6 = random_array6.reshape(5, 5)
print("Original random array 6:", random_array6)
print("Reshaped Array 6:\n", reshaped_arr6)

arr7 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped_arr7 = arr7.reshape(-1, 3)
print("Reshaped Array 7:\n", reshaped_arr7)

random_array8 = np.random.randint(1, 101, 15)
reshaped_arr8 = random_array8.reshape(3, 5)
print("Original random array 8:", random_array8)
print("Reshaped Array 8:\n", reshaped_arr8)

arr9 = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24])
reshaped_arr9 = arr9.reshape(6, -1)
print("Reshaped Array 9:\n", reshaped_arr9)

random_array10 = np.random.randint(1, 101, 18)
reshaped_arr10 = random_array10.reshape(3, 6)
print("Original random array 10:", random_array10)
print("Reshaped Array 10:\n", reshaped_arr10)


Reshaped Array 1:
 [[ 2  4  6  8]
 [10 12 14 16]]
Original random array 2: [ 75  88 100  24   3  22  53   2  88  30  38   2  64  60  21  33  76  58
  22  89]
Reshaped Array 2:
 [[ 75  88 100  24   3]
 [ 22  53   2  88  30]
 [ 38   2  64  60  21]
 [ 33  76  58  22  89]]
Reshaped Array 3:
 [[ 1  3  5  7]
 [ 9 11 13 15]]
Original random array 4: [49 91 59 42 92 60 80 15 62 62 47 62 51 55 64  3 51  7 21 73 39 18  4 89
 60 14  9 90 53  2]
Reshaped Array 4:
 [[49 91 59 42 92 60 80 15 62 62]
 [47 62 51 55 64  3 51  7 21 73]
 [39 18  4 89 60 14  9 90 53  2]]
Reshaped Array 5:
 [[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
Original random array 6: [84 92 60 71 44  8 47 35 78 81 36 50  4  2  6 54  4 54 93 63 18 90 44 34
 74]
Reshaped Array 6:
 [[84 92 60 71 44]
 [ 8 47 35 78 81]
 [36 50  4  2  6]
 [54  4 54 93 63]
 [18 90 44 34 74]]
Reshaped Array 7:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Original random array 8: [ 62 100  14  95  48  15  72  78  87  62  40  85  80  82  53]
Reshaped A

In [4]:
arr1 = np.array([[2, 4, 6, 8], [10, 12, 14, 16]])
reshaped_arr1 = arr1.flatten()
print("Reshaped Array 1:", reshaped_arr1)

random_array2 = np.random.randint(1, 100, (3, 6))
reshaped_arr2 = random_array2.flatten()
print("Original random array 2:\n", random_array2)
print("Reshaped Array 2:", reshaped_arr2)

arr3 = np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17]])
reshaped_arr3 = arr3.flatten()
print("Reshaped Array 3:", reshaped_arr3)

random_array4 = np.random.randint(1, 100, (4, 4))
reshaped_arr4 = random_array4.flatten()
print("Original random array 4:\n", random_array4)
print("Reshaped Array 4:", reshaped_arr4)

arr5 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
reshaped_arr5 = arr5.flatten()
print("Reshaped Array 5:", reshaped_arr5)

random_array6 = np.random.randint(1, 100, (5, 3))
reshaped_arr6 = random_array6.flatten()
print("Original random array 6:\n", random_array6)
print("Reshaped Array 6:", reshaped_arr6)

arr7 = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_arr7 = arr7.flatten()
print("Reshaped Array 7:", reshaped_arr7)

random_array8 = np.random.randint(1, 100, (3, 5))
reshaped_arr8 = random_array8.flatten()
print("Original random array 8:\n", random_array8)
print("Reshaped Array 8:", reshaped_arr8)

arr9 = np.array([[2, 4], [6, 8], [10, 12]])
reshaped_arr9 = arr9.flatten()
print("Reshaped Array 9:", reshaped_arr9)

random_array10 = np.random.randint(1, 100, (4, 4))
reshaped_arr10 = random_array10.flatten()
print("Original random array 10:\n", random_array10)
print("Reshaped Array 10:", reshaped_arr10)


Reshaped Array 1: [ 2  4  6  8 10 12 14 16]
Original random array 2:
 [[81  8 35 35 33  5]
 [41 28  7 73 72 12]
 [34 33 48 23 62 88]]
Reshaped Array 2: [81  8 35 35 33  5 41 28  7 73 72 12 34 33 48 23 62 88]
Reshaped Array 3: [ 1  3  5  7  9 11 13 15 17]
Original random array 4:
 [[37 99 44 86]
 [91 35 65 99]
 [47 78  3  1]
 [ 5 90 14 27]]
Reshaped Array 4: [37 99 44 86 91 35 65 99 47 78  3  1  5 90 14 27]
Reshaped Array 5: [ 2  4  6  8 10 12 14 16 18]
Original random array 6:
 [[ 9 79 15]
 [90 42 77]
 [51 63 96]
 [52 96  4]
 [94 23 15]]
Reshaped Array 6: [ 9 79 15 90 42 77 51 63 96 52 96  4 94 23 15]
Reshaped Array 7: [1 2 3 4 5 6]
Original random array 8:
 [[43 29 36 13 32]
 [71 59 86 28 66]
 [42 45 62 57  6]]
Reshaped Array 8: [43 29 36 13 32 71 59 86 28 66 42 45 62 57  6]
Reshaped Array 9: [ 2  4  6  8 10 12]
Original random array 10:
 [[28 28 44 84]
 [30 62 75 92]
 [89 62 97  1]
 [27 62 77  3]]
Reshaped Array 10: [28 28 44 84 30 62 75 92 89 62 97  1 27 62 77  3]
