In [1]:
import numpy as np

In [2]:
arr = np.random.randn(1,8)
arr

array([[ 0.61503852, -0.74975299,  1.26305721, -1.78847487,  2.00388187,
        -0.98707389,  0.83584579,  2.56918269]])

In [3]:
np.sqrt(arr)

C:\Users\HP840G~1\AppData\Local\Temp/ipykernel_18580/2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([[0.78424392,        nan, 1.12385818,        nan, 1.41558535,
               nan, 0.91424602, 1.60286702]])

In [4]:
arr

array([[ 0.61503852, -0.74975299,  1.26305721, -1.78847487,  2.00388187,
        -0.98707389,  0.83584579,  2.56918269]])

In [5]:
# inplace operation sqrt of arr and store in 2nd arr
np.sqrt(arr,arr)

C:\Users\HP840G~1\AppData\Local\Temp/ipykernel_18580/3108997181.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr,arr)


array([[0.78424392,        nan, 1.12385818,        nan, 1.41558535,
               nan, 0.91424602, 1.60286702]])

In [6]:
a = np.arange(0.1,6,1)
a

array([0.1, 1.1, 2.1, 3.1, 4.1, 5.1])

In [7]:
np.exp(a)

array([  1.10517092,   3.00416602,   8.16616991,  22.19795128,
        60.3402876 , 164.0219073 ])

In [8]:
# where pi comes from
# where exponents comes
# absolute value

In [9]:
n = 3 + 4j
np.abs(n)

5.0

In [10]:
np.abs(-0.2)

0.2

In [11]:
np.fabs(-0.2)

0.2

In [12]:
np.square(4)

16

In [13]:
# Logs three types
np.log(10)

2.302585092994046

In [14]:
np.log10(10)

1.0

In [15]:
np.log2(8)

3.0

In [16]:
np.log10(8)/np.log10(2)

3.0

In [17]:
# find sign
np.sign(arr)

array([[ 1., nan,  1., nan,  1., nan,  1.,  1.]])

In [18]:
np.ceil(0.9)

1.0

In [19]:
np.floor(0.9)

0.0

In [20]:
np.round(0.9)

1.0

In [21]:
np.round(0.49)

0.0

In [22]:
np.round(0.500001)

1.0

In [23]:
np.round(2.5)

2.0

In [24]:
# reciprcal
np.reciprocal(2)

0

In [25]:
np.reciprocal(0.2)

5.0

In [26]:
np.modf(1.33)

(0.33000000000000007, 1.0)

In [27]:
a,b = np.modf(1.33)

In [28]:
a,b

(0.33000000000000007, 1.0)

In [29]:
# trignometry functions
np.sin(np.pi/2)

1.0

In [30]:
np.cos(np.pi/2)

6.123233995736766e-17

In [31]:
np.arcsin(0.5)

0.5235987755982989

In [32]:
np.arctan2(2,-2)

2.356194490192345

In [33]:
x = np.array([1,0])
y = np.array([0,1])

np.arctan2(y,x)

array([0.        , 1.57079633])

In [34]:
(np.cos(0.2)) ** 2 + (np.sin(0.2)) ** 2

1.0

In [35]:
x = np.random.randn(1,6)
y = np.random.randn(1,6)

x

array([[-1.96028125, -0.26050766,  1.16842016,  2.74601217, -0.1410502 ,
         1.1426541 ]])

In [36]:
y

array([[-0.04952266,  1.09802034,  0.73167872,  0.99339401, -0.23584358,
         0.38206068]])

In [37]:
np.power(y, 3)

array([[-1.21453995e-04,  1.32382676e+00,  3.91706941e-01,
         9.80312658e-01, -1.31181372e-02,  5.57695371e-02]])

In [38]:
np.max(x)

2.7460121739577708

In [39]:
np.maximum(x,y)

array([[-0.04952266,  1.09802034,  1.16842016,  2.74601217, -0.1410502 ,
         1.1426541 ]])

In [40]:
0.1 + 0.2 == 0.3

False

In [41]:
0.1 + 0.2

0.30000000000000004

In [42]:
# comparison using floating point numbers
np.allclose(0.1+0.2,0.3)

True

In [43]:
np.mean(a)

0.33000000000000007

In [44]:
x.mean()

0.44920788795153843

In [45]:
x.std()

1.4680589531211123

In [46]:
x.var()

2.155197089839056

In [47]:
a = np.array([[5,2,3], [1,5,1], [9,2,3]])
a

array([[5, 2, 3],
       [1, 5, 1],
       [9, 2, 3]])

In [48]:
a.sum()

31

In [49]:
a.sum(axis=0)

array([15,  9,  7])

In [50]:
a.sum(axis=1)

array([10,  7, 14])

In [51]:
np.mean(a,axis=1)

array([3.33333333, 2.33333333, 4.66666667])

In [52]:
np.mean(a,axis=0)

array([5.        , 3.        , 2.33333333])

In [53]:
a.min(axis=0)

array([1, 2, 1])

In [54]:
a.max(axis=1)

array([5, 5, 9])

In [55]:
a.argmin()

3

In [56]:
a.argmax()

6

In [57]:
a.argmax(axis=0)

array([2, 1, 0], dtype=int64)

In [58]:
a = np.random.randn(2,5)
a

array([[-1.14440474, -1.9469992 ,  1.44252494,  0.13304243, -0.33094455],
       [ 0.59237594, -1.61630322, -0.09858879, -0.8113177 ,  0.70382656]])

In [59]:
a > 0

array([[False, False,  True,  True, False],
       [ True, False, False, False,  True]])

In [60]:
(a > 0 ).sum()

4

In [61]:
((a > 0) & (a < 1)).sum()

3

In [62]:
np.any(a>1)

True

In [63]:
x = np.linspace(-5,5,11)
x

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [64]:
# where condtion true do first operation and not true perform 2nd operation
np.where(x<0 ,x**2, x**3)

array([ 25.,  16.,   9.,   4.,   1.,   0.,   1.,   8.,  27.,  64., 125.])

In [65]:
np.select([x<-1, x<2, x>=2], [x, x**2, np.sqrt(x)])

C:\Users\HP840G~1\AppData\Local\Temp/ipykernel_18580/1237607202.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.select([x<-1, x<2, x>=2], [x, x**2, np.sqrt(x)])


array([-5.        , -4.        , -3.        , -2.        ,  1.        ,
        0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798])

In [66]:
a = np.sqrt(16)
a

4.0

In [67]:
b = np.abs(-5)
b

5

In [68]:
c = 3*a+b
c

17.0

# 2nd 
# Sorting in numpy

In [70]:
a = np.random.randn(6)
a

array([ 1.08672404,  0.21306057, -0.79472006,  2.95588316, -1.84461264,
        0.45114394])

In [74]:
a.sort()
a

array([-1.84461264, -0.79472006,  0.21306057,  0.45114394,  1.08672404,
        2.95588316])

In [75]:
arr = np.random.randn(5,3)
arr

array([[ 0.36770575, -0.05246131,  0.29280451],
       [-1.79714609, -2.08092472, -0.48834058],
       [ 0.45264759, -0.6906485 ,  0.07135031],
       [-0.829477  , -0.87778594,  1.17160435],
       [ 0.64173922,  1.08153908, -0.05657449]])

In [76]:
arr.sort()
arr

array([[-0.05246131,  0.29280451,  0.36770575],
       [-2.08092472, -1.79714609, -0.48834058],
       [-0.6906485 ,  0.07135031,  0.45264759],
       [-0.87778594, -0.829477  ,  1.17160435],
       [-0.05657449,  0.64173922,  1.08153908]])

In [77]:
arr.sort(axis=0)
arr

array([[-2.08092472, -1.79714609, -0.48834058],
       [-0.87778594, -0.829477  ,  0.36770575],
       [-0.6906485 ,  0.07135031,  0.45264759],
       [-0.05657449,  0.29280451,  1.08153908],
       [-0.05246131,  0.64173922,  1.17160435]])

In [78]:
arr = np.random.rand(3,5)
arr

array([[0.39538548, 0.11643136, 0.34697962, 0.77433761, 0.67559407],
       [0.78893746, 0.97308852, 0.62319262, 0.40428247, 0.8396301 ],
       [0.49664339, 0.33514415, 0.44278981, 0.66000875, 0.67122212]])

In [79]:
arr[:,0].sort()
arr

array([[0.39538548, 0.11643136, 0.34697962, 0.77433761, 0.67559407],
       [0.49664339, 0.97308852, 0.62319262, 0.40428247, 0.8396301 ],
       [0.78893746, 0.33514415, 0.44278981, 0.66000875, 0.67122212]])

In [81]:
arr[1,:].sort()
arr

array([[0.39538548, 0.11643136, 0.34697962, 0.77433761, 0.67559407],
       [0.33514415, 0.40428247, 0.49664339, 0.62319262, 0.8396301 ],
       [0.78893746, 0.97308852, 0.44278981, 0.66000875, 0.67122212]])

In [82]:
arr2 = arr.copy()
arr2.sort()
arr2

array([[0.11643136, 0.34697962, 0.39538548, 0.67559407, 0.77433761],
       [0.33514415, 0.40428247, 0.49664339, 0.62319262, 0.8396301 ],
       [0.44278981, 0.66000875, 0.67122212, 0.78893746, 0.97308852]])

In [83]:
arr

array([[0.39538548, 0.11643136, 0.34697962, 0.77433761, 0.67559407],
       [0.33514415, 0.40428247, 0.49664339, 0.62319262, 0.8396301 ],
       [0.78893746, 0.97308852, 0.44278981, 0.66000875, 0.67122212]])

In [84]:
a = np.random.randn(3,5)
a

array([[-0.36151701,  0.81783782, -1.54436402, -0.11919164, -0.20037147],
       [-0.76446217, -0.17591254, -0.22368776, -1.20036373,  0.23165224],
       [-0.17368485,  1.29106049, -0.618913  , -0.59945336, -2.56485681]])

In [85]:
a.sort(axis=1)
a

array([[-1.54436402, -0.36151701, -0.20037147, -0.11919164,  0.81783782],
       [-1.20036373, -0.76446217, -0.22368776, -0.17591254,  0.23165224],
       [-2.56485681, -0.618913  , -0.59945336, -0.17368485,  1.29106049]])

In [87]:
a[:,::-1]

array([[ 0.81783782, -0.11919164, -0.20037147, -0.36151701, -1.54436402],
       [ 0.23165224, -0.17591254, -0.22368776, -0.76446217, -1.20036373],
       [ 1.29106049, -0.17368485, -0.59945336, -0.618913  , -2.56485681]])

In [88]:
a

array([[-1.54436402, -0.36151701, -0.20037147, -0.11919164,  0.81783782],
       [-1.20036373, -0.76446217, -0.22368776, -0.17591254,  0.23165224],
       [-2.56485681, -0.618913  , -0.59945336, -0.17368485,  1.29106049]])

In [89]:
np.sort(a)

array([[-1.54436402, -0.36151701, -0.20037147, -0.11919164,  0.81783782],
       [-1.20036373, -0.76446217, -0.22368776, -0.17591254,  0.23165224],
       [-2.56485681, -0.618913  , -0.59945336, -0.17368485,  1.29106049]])

In [90]:
b = np.random.randn(5)
b

array([-1.91452072,  1.57061819, -0.41552317,  0.69990246, -0.40271901])

In [91]:
np.sort(b)

array([-1.91452072, -0.41552317, -0.40271901,  0.69990246,  1.57061819])

In [92]:
b

array([-1.91452072,  1.57061819, -0.41552317,  0.69990246, -0.40271901])

In [93]:
np.argsort(b)

array([0, 2, 4, 3, 1], dtype=int64)

In [94]:
values = np.array([5,0,1,3,2])
values

array([5, 0, 1, 3, 2])

In [95]:
indexer = values.argsort()
indexer

array([1, 2, 4, 3, 0], dtype=int64)

In [96]:
values[indexer]

array([0, 1, 2, 3, 5])

In [97]:
a = np.array([3,3,3,2,2,1,1,4,4])
a

array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [98]:
np.unique(a)

array([1, 2, 3, 4])

In [99]:
x = np.array([2,3,0,0,4,2,3,1])
y = np.array([1,1,0,2,2,2,3,5])
x

array([2, 3, 0, 0, 4, 2, 3, 1])

In [100]:
y

array([1, 1, 0, 2, 2, 2, 3, 5])

In [104]:
np.intersect1d(x,y)

array([0, 1, 2, 3])

In [105]:
np.union1d(x,y)

array([0, 1, 2, 3, 4, 5])

In [106]:
np.in1d(x,y)

array([ True,  True,  True,  True, False,  True,  True,  True])

In [107]:
x,y

(array([2, 3, 0, 0, 4, 2, 3, 1]), array([1, 1, 0, 2, 2, 2, 3, 5]))

In [108]:
np.setdiff1d(x,y)

array([4])

In [109]:
np.setxor1d(x,y)

array([4, 5])

In [113]:
a = np.random.randint(2,10,20)
a

array([5, 7, 8, 7, 9, 8, 5, 8, 4, 4, 7, 7, 9, 7, 9, 9, 7, 4, 7, 8])

In [114]:
# normal distribution
a = 10 * np.random.randn(3)
a

array([ -7.74163321, -11.78273745, -14.14380641])

In [115]:
a = np.random.standard_normal(3)
a

array([-0.5069562 , -1.39018692, -0.04030988])

In [116]:
# uniform distribution
a = np.random.rand(3)
a

array([0.36626375, 0.6556031 , 0.78888296])

In [117]:
a = np.random.uniform(0,10,3)
a

array([7.8147374 , 3.83984678, 9.50523535])

In [118]:
np.random.uniform(0,1,3)

array([0.74669282, 0.91109604, 0.56413593])

In [125]:
# Bionomial distribution
np.random.binomial(10,0.5,size=10)

array([5, 6, 4, 6, 2, 6, 5, 6, 4, 5])

In [128]:
np.random.binomial(15,1/6,size=5)

array([3, 2, 2, 3, 2])

In [140]:
# seed generate fixed random numbers 
np.random.seed(47)
np.random.randn(3)

array([-0.84800948,  1.30590636,  0.92420797])

In [145]:
r = np.random.RandomState(42)
r.randn(3)

array([ 0.49671415, -0.1382643 ,  0.64768854])

In [146]:
# reshaping arrays
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [147]:
a.shape

(15,)

In [149]:
b = a.reshape(5,-1)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [150]:
b.shape

(5, 3)

In [151]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [153]:
z = c.reshape(6,2)
z

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])