# Task: 1

In [1]:
import numpy as np

t1 = 3 * np.sqrt(16) + np.abs(-5)
print(t1)

17.0


In [2]:
t2 = 23 - np.log10(100) + np.abs(-2)
print(t2)

23.0


In [3]:
t3 = np.sqrt(25) + 1 / (2 * 4)
print(t3)

5.125


In [4]:
t4 = np.abs(-3 * np.log2(8)) + np.sqrt(144)
print(t4)

21.0


In [5]:
t5 = np.exp(2) + np.log(np.e**10) - 1
print(t5)

16.389056098930652


In [6]:
t6 = np.sqrt(81) + np.log2(32) - 32
print(t6)

-18.0


In [7]:
t7 = np.abs(np.log(1)) + 1 / np.sqrt(9) + np.exp(0)
print(t7)

1.3333333333333333


In [8]:
t8 = 4 * np.sqrt(36) - np.log(1) + np.abs(-4)
print(t8)

28.0


In [9]:
t9 = np.sqrt(49) + 1 / (2 * np.exp(2)) - np.abs(np.log10(100))
print(t9)

5.067667641618306


In [10]:
t10 = 33 + np.log2(16) - np.abs(-np.sqrt(64))
print(t10)

29.0


# Task: 2

In [11]:
A = np.array([2, 4, 6])

t1 = A**2 + np.sqrt(A) - np.abs(A)
print(t1)


[ 3.41421356 14.         32.44948974]


In [12]:
B = np.array([1, 3, 5])

t2 = np.exp(B) - np.log10(B) + np.abs(B)
print(t2)


[  3.71828183  22.60841567 152.7141891 ]


In [13]:
C = np.array([0.1, 0.5, 1.0])

t3 = np.sqrt(C) + 1 / C**2 - np.log(C)
print(t3)

[102.61881286   5.40025396   2.        ]


In [14]:
D = np.array([-2, 0, 2])

t4 = np.abs(D) + np.sqrt(D) - np.log2(np.abs(D))
print(t4)

[       nan        inf 2.41421356]


C:\Users\HP840G~1\AppData\Local\Temp/ipykernel_14440/1355664005.py:3: RuntimeWarning: invalid value encountered in sqrt
  t4 = np.abs(D) + np.sqrt(D) - np.log2(np.abs(D))
C:\Users\HP840G~1\AppData\Local\Temp/ipykernel_14440/1355664005.py:3: RuntimeWarning: divide by zero encountered in log2
  t4 = np.abs(D) + np.sqrt(D) - np.log2(np.abs(D))


In [15]:
E = np.array([1, 2, 3])

t5 = np.exp(E) + np.log(E) - 1 / np.abs(E)
print(t5)

[ 1.71828183  7.58220328 20.85081588]


In [16]:
F = np.array([4, 9, 16])

t6 = np.sqrt(F) + np.log2(F) - F**(1/2)
print(t6)

[2.       3.169925 4.      ]


In [17]:
G = np.array([0.2, 0.4, 0.6])

t7 = np.abs(G) + np.sqrt(G) - 1 / np.log10(G)
print(t7)

[2.07789015 3.54539713 5.88217222]


In [18]:
H = np.array([-3, -2, -1])
t8 = np.exp(H) + np.log(np.abs(H)) - np.sqrt(np.abs(H))
print(t8)

[-0.58365145 -0.5857311  -0.63212056]


In [19]:
I = np.array([0.5, 1.0, 1.5])

t9 = I**2 + 1 / I - np.log2(I)
print(t9)


[3.25       2.         2.33170417]


In [20]:
J = np.array([2, 4, 8])

t10 = np.abs(J) + np.sqrt(J) - J**(1/3)
print(10)

10


# Task : 3


In [21]:
temperature = np.array([-3.4, 2.7, -1.2])

t1 = np.sqrt(temperature)
t1[np.isnan(t1)] = 0  
print(t1)

[0.         1.64316767 0.        ]


C:\Users\HP840G~1\AppData\Local\Temp/ipykernel_14440/3699846443.py:3: RuntimeWarning: invalid value encountered in sqrt
  t1 = np.sqrt(temperature)


In [22]:

mm = np.array([4.8, -7.2, 5.5])

t2 = np.sqrt(mm)
t2[np.isnan(t2)] = np.nan  
print(t2)

ms = np.array([0.9, -2.3, 6.7])

t3 = 1 / ms
t3[np.isnan(t3)] = 0  
print(t3)

km = np.array([-0.6, 3.2, -4.1])

t4 = np.log(km)
t4[np.isnan(t4)] = np.nan  
print(t4)

time = np.array([2.4, -1.8, 7.9])

t5 = 1 / time
t5[np.isnan(t5)] = 0  
print(t5)

ph = np.array([-5.5, 4.3, 6.1])

t6 = np.log10(np.abs(ph))
t6[np.isnan(t6)] = 0  
print(t6)

[2.19089023        nan 2.34520788]
[ 1.11111111 -0.43478261  0.14925373]
[       nan 1.16315081        nan]
[ 0.41666667 -0.55555556  0.12658228]
[0.74036269 0.63346846 0.78532984]


C:\Users\HP840G~1\AppData\Local\Temp/ipykernel_14440/3536337559.py:3: RuntimeWarning: invalid value encountered in sqrt
  t2 = np.sqrt(mm)
C:\Users\HP840G~1\AppData\Local\Temp/ipykernel_14440/3536337559.py:15: RuntimeWarning: invalid value encountered in log
  t4 = np.log(km)


# Task:4

In [23]:
t1 = np.tan(np.pi/3) * 1/np.sin(np.pi/4)
print(t1)

2.449489742783177


In [24]:
t2 = np.arcsin(1/2) + np.arccos(np.sqrt(3)/2)
print(t2)

1.0471975511965979


In [25]:
t3 = np.arccos(1/np.sqrt(2)) * np.arcsin(1)
print(t3)


1.23370055013617


In [26]:
t4 = np.tan(np.arccos(2/3)) - 1/np.tan(np.arcsin(4/5))
print(t4)

0.36803398874989524


In [27]:
t5 = 1/np.cos(np.arctan(3)) * 1/np.sin(np.arcsin(1/2))
print(t5)

6.324555320336758


# Task:5

In [28]:
test_scores = np.array([
    [85, 90, 88],
    [92, 89, 78],
    [95, 91, 87]
])

mean = np.mean(test_scores, axis=0)
std = np.std(test_scores, axis=0)
print(mean)
print(std)


[90.66666667 90.         84.33333333]
[4.18993503 0.81649658 4.49691252]


In [29]:
sales = np.array([
    [120, 150, 180],
    [90, 110, 130],
    [200, 220, 240]
])

median = np.median(sales, axis=1)
total = np.sum(sales, axis=1)
print(median)
print(total)

[150. 110. 220.]
[450 330 660]


In [30]:
temperature = np.array([
    [
        [22, 25, 21],
        [20, 23, 22],
        [24, 26, 25]
    ],
    [
        [23, 24, 22],
        [25, 27, 26],
        [28, 29, 30]
    ]
])

variance = np.var(temperature, axis=0)
sum1 = np.sum(temperature, axis=0)
print(variance)
print(sum1)


[[0.25 0.25 0.25]
 [6.25 4.   4.  ]
 [4.   2.25 6.25]]
[[45 49 43]
 [45 50 48]
 [52 55 55]]


In [31]:
times = np.array([
    [
        [350, 400, 380],
        [420, 390, 410]
    ],
    [
        [390, 370, 400],
        [410, 430, 380]
    ]
])

median = np.median(times, axis=1)
total = np.sum(times, axis=1)
print(median)
print(total)

[[385. 395. 395.]
 [400. 400. 390.]]
[[770 790 790]
 [800 800 780]]


In [32]:
weights = np.array([
    [
        [65, 70, 68],
        [72, 75, 73]
    ],
    [
        [68, 71, 70],
        [74, 77, 76]
    ]
])

mean = np.mean(weights, axis=2)
variance = np.var(weights, axis=2)
print(mean)
print(variance)

[[67.66666667 73.33333333]
 [69.66666667 75.66666667]]
[[4.22222222 1.55555556]
 [1.55555556 1.55555556]]


# Task:6

In [33]:
np.random.seed(42)
actual = 10 * np.random.randn(10)
estimated = actual + 0.1 * np.random.randn(10)
print("Actual Data:", actual)
print("Estimated Data:", estimated)

Actual Data: [ 4.96714153 -1.38264301  6.47688538 15.23029856 -2.34153375 -2.34136957
 15.79212816  7.67434729 -4.69474386  5.42560044]
Estimated Data: [ 4.92079976 -1.42921599  6.50108161 15.03897054 -2.51402553 -2.39759832
 15.69084504  7.70577202 -4.78554627  5.28437007]


In [34]:
errors = estimated - actual
print("Errors:", errors)

sum_of_errors = np.sum(errors)
print("Sum of Errors:", sum_of_errors)

avg_sum_of_squares = np.mean(errors**2)
print("Average Sum of Squares of Errors:", avg_sum_of_squares)

rmse = np.sqrt(avg_sum_of_squares)
print("Root Mean Square Error (RMSE):", rmse)

Errors: [-0.04634177 -0.04657298  0.02419623 -0.19132802 -0.17249178 -0.05622875
 -0.10128311  0.03142473 -0.09080241 -0.14123037]
Sum of Errors: -0.790658234582414
Average Sum of Squares of Errors: 0.011386043722185442
Root Mean Square Error (RMSE): 0.1067054062462884


# Task:7

In [37]:
np.random.seed(42)
true_labels = np.random.randint(2, size=100)
predicted = np.random.rand(100)

epsilon = 1e-15
predicted = np.maximum(epsilon, np.minimum(1 - epsilon, predicted))

log_loss = -np.mean(true_labels * np.log(predicted) + (1 - true_labels) * np.log(1 - predicted))
print("Log Loss:", log_loss)


Log Loss: 1.0277373670101957
