# Task:1

In [1]:
import numpy as np
arr_1 = np.array([[3,6,9],[12,15,18],[21,24,27]])
arr_1.flatten()

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [2]:
matrix = np.random.rand(3,4)
flat = matrix.flatten()
flat

array([0.83545077, 0.07162596, 0.92496297, 0.48750357, 0.47786482,
       0.06355264, 0.06638488, 0.23278922, 0.58182893, 0.26085806,
       0.50638359, 0.91778841])

In [3]:
arr = np.array([[[2, 4], [6, 8]], [[1, 3], [5, 7]]])
flat = arr.flatten()
flat

array([2, 4, 6, 8, 1, 3, 5, 7])

In [4]:
arr3 = np.random.random((2, 3, 2))
arr = arr3.flatten()
arr

array([0.77276715, 0.69091814, 0.42913992, 0.91099156, 0.95837974,
       0.23701463, 0.21735434, 0.80627475, 0.17006721, 0.30112848,
       0.03022258, 0.60325966])

In [5]:
arr_3 = np.array([[5,10,15],[20,25,30],[35,40,45]])
flat = arr_3.flatten()
flat

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

# Task:2

In [6]:
arr1 = [2, 4, 6, 8, 10]
arr2 = [1, 3, 5, 7, 9]

stack = np.stack((arr1,arr2),axis=0)
stack

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [7]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)

stack = np.stack((arr1, arr2),axis=1)
stack

array([[[0.52034054, 0.02476121, 0.40823701, 0.20826675],
        [0.40533961, 0.56170583, 0.75059717, 0.02595539]],

       [[0.17386616, 0.79997939, 0.18855241, 0.89080647],
        [0.08844935, 0.75765962, 0.82419526, 0.20408981]],

       [[0.23008405, 0.83648363, 0.81166175, 0.83794146],
        [0.35591968, 0.17594356, 0.97359872, 0.65315546]]])

In [8]:
arr_3 = np.array([[1,2],[3,4]])
arr_4 = np.array([[5,6],[7,8]])

stack = np.stack((arr_3,arr_4),axis=0)
stack

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
arr1 = np.random.rand(5) 
arr2 = np.random.rand(5)

stack = np.hstack((arr1, arr2))
stack

array([0.79948058, 0.99171754, 0.0516897 , 0.4609017 , 0.93128987,
       0.80028486, 0.61003697, 0.50708498, 0.26846789, 0.44060666])

In [10]:
arr5 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr6 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

stack = np.stack((arr5, arr6),axis=1)
stack

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 9, 10],
         [11, 12]]],


       [[[ 5,  6],
         [ 7,  8]],

        [[13, 14],
         [15, 16]]]])

In [11]:
arr7 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr8 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

stack = np.vstack((arr7, arr8))
stack

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

# Task : 3

In [12]:
arr1 = [2, 4, 6, 8, 10]
arr2 = [1, 3, 5, 7, 9]
product = np.dot(arr1,arr2)
product

190

In [13]:
matrix = np.random.rand(3, 3)
matrix

array([[0.80605339, 0.08531481, 0.32701828],
       [0.88838561, 0.11444491, 0.76536978],
       [0.19272049, 0.38853513, 0.47975942]])

In [14]:
inverse = np.linalg.inv(matrix)
inverse

array([[ 2.13522992, -0.758462  , -0.2454466 ],
       [ 2.45438589, -2.85048887,  2.87445942],
       [-2.84542133,  2.61315602, -0.14491819]])

In [15]:
arr3 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

Q, R = np.linalg.qr(arr3)
Q, R

(array([[-0.12309149,  0.90453403,  0.40824829],
        [-0.49236596,  0.30151134, -0.81649658],
        [-0.86164044, -0.30151134,  0.40824829]]),
 array([[-8.12403840e+00, -9.60113630e+00, -1.10782342e+01],
        [ 0.00000000e+00,  9.04534034e-01,  1.80906807e+00],
        [ 0.00000000e+00,  0.00000000e+00, -1.11164740e-15]]))

In [16]:
matrix = np.random.rand(4,4)
matrix

array([[0.40891304, 0.36703473, 0.43940163, 0.05100349],
       [0.52178794, 0.91981712, 0.77464277, 0.64499003],
       [0.78395344, 0.65156594, 0.37747033, 0.99023396],
       [0.32250334, 0.62093071, 0.72528362, 0.69701228]])

In [17]:
diagonal = np.diag(matrix)
diagonal

array([0.40891304, 0.91981712, 0.37747033, 0.69701228])

In [18]:
arr4 = np.array([[2,4,6],[8,10,12],[14,16,18]])
print(arr4)

trace = np.trace(arr4)
print(trace)

product = np.dot(arr4,arr4)
print(product)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
30
[[120 144 168]
 [264 324 384]
 [408 504 600]]


In [19]:
matrix = np.random.randint(1, 10, (3, 3))
determinant = np.linalg.det(matrix)
determinant

119.00000000000003

In [20]:
arr_5 = np.array([[1,2],[3,4]])
arr_5

array([[1, 2],
       [3, 4]])

In [21]:
L, S, R = np.linalg.svd(arr_5)

In [22]:
L

array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]])

In [23]:
S

array([5.4649857 , 0.36596619])

In [24]:
R

array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]])

In [25]:
L@(np.diag(S))@R

array([[1., 2.],
       [3., 4.]])

In [26]:
matrix = np.random.rand(4,4)
matrix
w, v = np.linalg.eig(matrix)

In [27]:
w

array([ 1.63045478+0.j        ,  0.55380083+0.j        ,
       -0.41115788+0.20805338j, -0.41115788-0.20805338j])

In [28]:
w.shape

(4,)

In [29]:
v

array([[ 0.3564296 +0.j        ,  0.51587957+0.j        ,
        -0.14940652-0.00574901j, -0.14940652+0.00574901j],
       [ 0.38754968+0.j        , -0.57523808+0.j        ,
        -0.02711712-0.46450436j, -0.02711712+0.46450436j],
       [ 0.54455991+0.j        , -0.33046171+0.j        ,
        -0.18629071+0.55929113j, -0.18629071-0.55929113j],
       [ 0.65285349+0.j        , -0.54200045+0.j        ,
         0.643144  +0.j        ,  0.643144  -0.j        ]])

In [30]:
v.shape

(4, 4)

In [31]:
matrix = np.random.rand(5,5)
matrix

array([[0.18173516, 0.90582008, 0.7142415 , 0.27875305, 0.32708857],
       [0.04515372, 0.60420218, 0.52590562, 0.01050443, 0.97774027],
       [0.14316248, 0.02676894, 0.35262912, 0.9346639 , 0.08842118],
       [0.05964535, 0.9618233 , 0.69266551, 0.88517323, 0.21118615],
       [0.06484688, 0.43127027, 0.82681074, 0.0014221 , 0.05097335]])

In [32]:
np.linalg.norm(matrix)

2.6996479672348483

In [33]:
np.linalg.norm(matrix,axis=0)

array([0.25164401, 1.51571269, 1.44030082, 1.31717269, 1.05734533])

In [34]:
np.linalg.norm(matrix, axis=1)

array([1.24433468, 1.26481707, 1.0133974 , 1.49551943, 0.93617064])

# Task:4

In [41]:
a = np.array([[2, 3], [4, -1]])
b = np.array([8, 6])
x = np.linalg.solve(a, b)
x

array([1.85714286, 1.42857143])

In [42]:
a = np.array([[1, 1, 1], [2, -1, 3], [3, 2, -2]])
b = np.array([6, 5, 4])
x = np.linalg.solve(a, b)
x

array([0.75  , 3.0625, 2.1875])

In [43]:
a = np.array([[1, 1, 1, 1], [2, -1, 3, -1], [3, 2, 2, 1], [4, -3, 1, -2]])
b = np.array([10, 3, 17, 1])
x = np.linalg.solve(a,b)
x

array([ 3.00000000e+00, -5.87765131e-16,  1.00000000e+00,  6.00000000e+00])

In [44]:
a = np.array([[3, 4], [2, -5]])
b = np.array([14, -1])
x = np.linalg.solve(a,b)
x

array([2.86956522, 1.34782609])

In [45]:
a = np.array([[2, -1, 1], [4, 2, -3], [-2, 3, 2]])
b = np.array([8, 6, 2])
x = np.linalg.solve(a, b)
x

array([3.09090909, 0.90909091, 2.72727273])

In [46]:
a = np.array([[1, 1, -1, 1], [2, -1, 3, 1], [1, 2, -2, -1], [4, -3, 1, 2]])
b = np.array([3, 7, -1, 5])
x = np.linalg.solve(a,b)
x

array([1. , 1.5, 1.5, 2. ])

# Task: 5

In [47]:
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([3, 7, 11, 15])

x_bias = np.c_[np.ones(x.shape[0]), x]

weights_and_bias = np.linalg.lstsq(x_bias, y, rcond=None)[0]

x_new = np.array([[10, 12], [13, 14]])
x_new_bias = np.c_[np.ones(x_new.shape[0]), x_new]

predictions = np.dot(x_new_bias, weights_and_bias)

print("Weights and Bias:", weights_and_bias)
print("Predictions for new data:", predictions)


Weights and Bias: [-1.04032624e-16  1.00000000e+00  1.00000000e+00]
Predictions for new data: [22. 27.]
