# Numpy Fundamentals

- **Date:** November 7, 2023
- **Author:** Dr. Muhammad Abbas Abbasi
- **Institute:** DeepEmbed Lab, Department of Electronic Engineering, IUB


In [2]:
# import numpy
import numpy as np

# Arrays Indexing

## Array attributes

In [3]:
x = np.array([[1,2, 1], [3,4, 2],[5,6, 3]])
x

array([[1, 2, 1],
       [3, 4, 2],
       [5, 6, 3]])

In [4]:
x.shape

(3, 3)

In [5]:
x.ndim

2

In [6]:
x.nbytes

36

In [7]:
x.dtype

dtype('int32')

### Array operations

In [8]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [9]:
arr1**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [10]:
arr2 = np.full((2,5),arr1)
arr2

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [11]:
arr3 = arr2
arr3

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [13]:
arr3[0,:] = 1 + arr2[0,:]
arr3

array([[2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4]])

In [14]:
arr2

array([[2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4]])

In [15]:
arr3 == arr2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

### Slicing

In [16]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
a[4:7]

array([4, 5, 6])

In [18]:
a[4:7]=9

In [19]:
a

array([0, 1, 2, 3, 9, 9, 9, 7])

In [20]:
a_slice = a[4:7]
a_slice

array([9, 9, 9])

In [21]:
a_slice[1] = 11
a_slice

array([ 9, 11,  9])

In [22]:
a

array([ 0,  1,  2,  3,  9, 11,  9,  7])

In [23]:
a_slice[:] = 13

In [24]:
a

array([ 0,  1,  2,  3, 13, 13, 13,  7])

In [ ]:
a_slice_copy = a_slice.copy()

In [ ]:
a_slice_copy

In [ ]:
a_slice_copy[:]=15

In [ ]:
a

In [ ]:
a_slice[:]=17

In [ ]:
a

In [ ]:
a_slice=19

In [ ]:
a

In [ ]:
a_slice_copy

In [ ]:
a_slice

### Slicing Example

In [25]:
a = np.array([np.arange(i, i + 6) for i in range(0, 60, 10)])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [26]:
b = a[1:5,1:5]
b

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [27]:
b[:,:]=0
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [28]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

### Slicing expressions

In [29]:
a = np.arange(80).reshape(8,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [30]:
a.shape

(8, 10)

In [31]:
a[3]    # row selection

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [32]:
a[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [33]:
a[:,3]    # column selection

array([ 3, 13, 23, 33, 43, 53, 63, 73])

In [34]:
a[::2]  # every 2nd row

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [35]:
a[3::]   # from 3rd row onwards

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [36]:
a[:,::2]  # every 2nd column

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78]])

In [37]:
a[:,3::] # 3rd column onwards

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49],
       [53, 54, 55, 56, 57, 58, 59],
       [63, 64, 65, 66, 67, 68, 69],
       [73, 74, 75, 76, 77, 78, 79]])

### Indexing 3D arrays

In [38]:
a = np.arange(60).reshape(3,4,5)   # 3 blocks of 4x5 size
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [39]:
a[0,:,:] # block 0

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
a[0,...]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
a[:,2,:] # 2nd row from each block

array([[10, 11, 12, 13, 14],
       [30, 31, 32, 33, 34],
       [50, 51, 52, 53, 54]])

In [42]:
a[:,:,3] # every column is converted to a row

array([[ 3,  8, 13, 18],
       [23, 28, 33, 38],
       [43, 48, 53, 58]])

In [43]:
a[...,3]

array([[ 3,  8, 13, 18],
       [23, 28, 33, 38],
       [43, 48, 53, 58]])

### 3D array indexing example 2

In [44]:
import numpy as np
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [45]:
arr.shape

(2, 3, 4)

In [46]:
arr[:,:,:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [47]:
arr[:,:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [48]:
arr[:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [49]:
arr[:,]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### Boolean indexing

In [50]:
names = np.array(['Ali', 'Kashif', 'Sohail', 'Anam', 'Saba', 'Rida'])
names

array(['Ali', 'Kashif', 'Sohail', 'Anam', 'Saba', 'Rida'], dtype='<U6')

In [51]:
names == 'Saba'

array([False, False, False, False,  True, False])

In [52]:
names == 'Ali'

array([ True, False, False, False, False, False])

In [53]:
mask = (names=='Saba')|(names=='Ali')
mask

array([ True, False, False, False,  True, False])

In [54]:
data = np.random.randn(6,3)
data

array([[ 1.79120818e+00, -6.92827824e-04, -3.22637350e-01],
       [-7.29402688e-02,  1.59839855e+00, -9.19783914e-01],
       [ 1.91870958e+00,  1.16252259e-03, -1.24910905e+00],
       [ 8.24843435e-02, -3.82047617e-02, -3.44397141e-01],
       [ 4.21585057e-01, -2.67646073e-01,  1.48874296e+00],
       [ 1.65361438e+00, -5.36411875e-01, -1.31211853e+00]])

In [55]:
data[mask, :] # mask is applied on all columns

array([[ 1.79120818e+00, -6.92827824e-04, -3.22637350e-01],
       [ 4.21585057e-01, -2.67646073e-01,  1.48874296e+00]])

In [56]:
data[~mask, :]   # Slicing on the basis of False

array([[-7.29402688e-02,  1.59839855e+00, -9.19783914e-01],
       [ 1.91870958e+00,  1.16252259e-03, -1.24910905e+00],
       [ 8.24843435e-02, -3.82047617e-02, -3.44397141e-01],
       [ 1.65361438e+00, -5.36411875e-01, -1.31211853e+00]])

In [57]:
data

array([[ 1.79120818e+00, -6.92827824e-04, -3.22637350e-01],
       [-7.29402688e-02,  1.59839855e+00, -9.19783914e-01],
       [ 1.91870958e+00,  1.16252259e-03, -1.24910905e+00],
       [ 8.24843435e-02, -3.82047617e-02, -3.44397141e-01],
       [ 4.21585057e-01, -2.67646073e-01,  1.48874296e+00],
       [ 1.65361438e+00, -5.36411875e-01, -1.31211853e+00]])

In [58]:
data[data<0]=0


In [59]:
data

array([[1.79120818e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.59839855e+00, 0.00000000e+00],
       [1.91870958e+00, 1.16252259e-03, 0.00000000e+00],
       [8.24843435e-02, 0.00000000e+00, 0.00000000e+00],
       [4.21585057e-01, 0.00000000e+00, 1.48874296e+00],
       [1.65361438e+00, 0.00000000e+00, 0.00000000e+00]])

### Integer lists as indices

In [60]:
arr = np.empty((6,4))
for i in range(6):
    arr[i]=i*i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.],
       [ 9.,  9.,  9.,  9.],
       [16., 16., 16., 16.],
       [25., 25., 25., 25.]])

In [61]:
arr[[2, 0, 4, 2, 0]]

array([[ 4.,  4.,  4.,  4.],
       [ 0.,  0.,  0.,  0.],
       [16., 16., 16., 16.],
       [ 4.,  4.,  4.,  4.],
       [ 0.,  0.,  0.,  0.]])

In [62]:
arr[[-4, -1, -4, -3]]  # row counting backwards

array([[ 4.,  4.,  4.,  4.],
       [25., 25., 25., 25.],
       [ 4.,  4.,  4.,  4.],
       [ 9.,  9.,  9.,  9.]])

### Differences between Python Lists and Numpy Arrays

In [63]:
a = [1, 2, 3]
a

[1, 2, 3]

In [64]:
b=a
b

[1, 2, 3]

In [65]:
a == b

True

In [66]:
a is b

True

In [67]:
c = a[:]    # copy
c

[1, 2, 3]

In [68]:
a is c

False

In [69]:
a==c

True

In [70]:
d = a.copy()
d

[1, 2, 3]

In [71]:
a is d

False

In [72]:
a == d

True

In [ ]:
a

In [ ]:
a[1:2] = [5,6]
a

In [ ]:
a1 = np.arange(1,4)
a1

In [ ]:
a1[1:2] = [5,6]

### Broadcasting

In [ ]:
a = np.arange(5).reshape(5,1)
a

In [ ]:
a.shape

In [ ]:
b = np.arange(6).reshape(1,6)
b

In [ ]:
b.shape

In [ ]:
a+b   # a will be broadcasted to 5,6 and b will be broadcasted tp 5,6

In [ ]:
(a+b).shape

In [ ]:
c=np.arange(6)
c

In [ ]:
c.shape

In [ ]:
a.shape

In [ ]:
a+c  # c will be broadcasted to 5,6

In [ ]:
d = 10
d

In [ ]:
a+d  # d will be broadcasted to 1,1 and then 5,1

### Broadcasting example

In [ ]:
arr = np.arange(6).reshape(3,2)
arr

In [ ]:
arr.shape

In [ ]:
col_mean = arr.mean(0)
col_mean

In [ ]:
col_mean.shape

In [ ]:
col_demean = arr - col_mean
col_demean

In [ ]:
col_demean.mean(0)

### Expanding dimensions

In [ ]:
x = np.array([1,2,3])
x

In [ ]:
x.shape

In [ ]:
# We want to expand it to 1,3
y = np.expand_dims(x, axis=0)
y

In [ ]:
y.shape

In [ ]:
z=np.expand_dims(x, axis=1)
z

In [ ]:
z.shape

In [ ]:
y=np.expand_dims(x, axis=(0,1))
y

In [ ]:
y.shape

In [ ]:
z = np.expand_dims(x,axis=(1,0))
z

In [ ]:
z.shape

In [ ]:
y=np.expand_dims(x,axis=(0,2))
y

In [ ]:
y.shape

In [ ]:
y=np.expand_dims(x,axis=(1,2))
y

In [ ]:
y.shape

In [ ]:
y=np.expand_dims(x,axis=(0,2,3))
y

In [ ]:
y.shape

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
x

In [ ]:
x.shape

In [ ]:
y=np.expand_dims(x,axis=0)
y

In [ ]:
y.shape

In [ ]:
y=np.expand_dims(x,axis=(0,3))
y

In [ ]:
y.shape

### Transpose

In [ ]:
arr = np.arange(15).reshape(3,5)
arr

In [ ]:
arr.shape

In [ ]:
arr.T

In [ ]:
# transpose of a vector
a = np.arange(6)
a

In [ ]:
a.T

In [ ]:
a.shape

In [ ]:
a.T.shape

In [ ]:
arr

In [ ]:
arr.transpose(1,0)

In [ ]:
x = np.arange(24).reshape(3,2,4)
x

In [ ]:
x.transpose(0,1,2)

In [ ]:
x.transpose(0,2,1)  # 2nd and 3rd dimensions swapped

In [ ]:
x.shape

In [ ]:
x

In [ ]:
x.transpose(1,0,2)  # dimension 0 and 1 swapped 

In [ ]:
x.transpose(2,1,0)

### Array manipulations

In [ ]:
arr = np.arange(15).reshape(5,3)
arr

In [ ]:
np.fliplr(arr)

In [ ]:
np.flipud(arr)

In [ ]:
np.rot90(arr)

In [ ]:
arr

In [ ]:
np.rot90(np.fliplr(arr))