# Numpy Fundamentals

- **Date:** November 16, 2023
- **Author:** Dr. Muhammad Abbas Abbasi
- **Institute:** DeepEmbed Lab, Department of Electronic Engineering, IUB


In [ ]:
# import numpy
import numpy as np

### Flattening Arrays

In [ ]:
x = np.arange(15).reshape(5,3)
x

In [ ]:
x.shape

In [ ]:
y = x.ravel()
y

In [ ]:
y.shape

In [ ]:
x

In [ ]:
y[0]=99

In [ ]:
y

In [ ]:
x

Ravel method does not produce acopy
We use flatten method which produces copy

In [ ]:
x

In [ ]:
z = x.flatten()
z

In [ ]:
z[0] = -100

In [ ]:
z

In [ ]:
x

### Concatenating Arrays

In [ ]:
arr1 = np.arange(1,7).reshape(2,3)
arr1

In [ ]:
arr2 = np.arange(7,13).reshape(2,3)
arr2

In [ ]:
np.concatenate([arr1,arr2], axis=0)

In [ ]:
np.concatenate([arr1,arr2], axis=1)

### Stacking

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
np.vstack((arr1,arr2))

In [ ]:
np.row_stack((arr1,arr2))

In [ ]:
np.hstack((arr1,arr2))

In [ ]:
np.column_stack((arr1,arr2))

### Stacking lower order arrays to create higher order arrays

In [1]:
import numpy as np
a1 = np.arange(1,13)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [2]:
a1.shape

(12,)

In [3]:
a2 = np.arange(13,25)
a2

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [4]:
a2.shape

(12,)

In [5]:
a3 = np.stack((a1,a2), axis=0)  # column-wise stacling of elements
a3

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
a3.shape

In [ ]:
a4 = np.stack((a1,a2), axis=1) # row-wise stacking of elements
a4

In [ ]:
a4.shape

In [ ]:
x1 = np.arange(1,13).reshape(3,4)
x1

In [ ]:
x1.shape

In [ ]:
x2 = np.arange(13,25).reshape(3,4)
x2

In [ ]:
x2.shape

In [ ]:
x3 = np.stack((x1,x2), axis=0)
x3

In [ ]:
x3.shape

In [ ]:
x4 = np.stack((x1,x2), axis=1)
x4

In [ ]:
x4.shape

In [ ]:
x5 = np.stack((x1,x2), axis=2)
x5

In [ ]:
x5.shape

# Linear Algebra

### Dot product

In [ ]:
a = np.arange(1,5)
a

In [ ]:
b = np.arange(5,9)
b

In [ ]:
np.dot(a,b)

In [ ]:
a@b

In [ ]:
x = np.arange(1,7).reshape(2,3)
x

In [ ]:
y = np.ones(3)
y

In [ ]:
x@y

In [ ]:
p = np.random.randint(0,10,(4,4))
p

In [ ]:
q = np.random.randint(-5,5,(4,4))
q

In [ ]:
p@q   # normal matrix multiplication

### Inverse of a matrix

In [ ]:
np.linalg.inv(p)

### QR Decomposition of a matrix

In [ ]:
q,r = np.linalg.qr(p)  # used in curve fitting or regression (least squares)

In [ ]:
q  # orthogonal matrix i.e. its transpose is equal to its inverse

In [ ]:
q.T

In [ ]:
np.linalg.inv(q)

In [ ]:
r

In [ ]:
q@r

In [ ]:
p

### Diagonal and trace

In [ ]:
p

In [ ]:
np.diag(p)

In [ ]:
np.trace(p)

### Eigenvalues and eigenvectors of a square matrix

In [ ]:
p

In [ ]:
w, v = np.linalg.eig(p)

In [ ]:
w

In [ ]:
w.shape

In [ ]:
v

In [ ]:
v.shape

### Singular value decomposition

In [ ]:
p

In [ ]:
L, S, R = np.linalg.svd(p)

In [ ]:
L

In [ ]:
S

In [ ]:
R

In [ ]:
L@(np.diag(S))@R

### Solving Linear Systems of Equations
\begin{equation}
3x-y-z=0\\
x+y=5\\
2x-3z=2
\end{equation}

In [ ]:
A=np.array([[3,-1,-1],[1,1,0],[2,0,-3]])
A

In [ ]:
b=np.array([[0],[5],[2]])
b

In [ ]:
np.linalg.solve(A,b)

### Computing norms

In [ ]:
x = np.array([[0,3,4],[2,6,4]])
x

In [ ]:
np.linalg.norm(x)  # norm of all glgmgnts

In [ ]:
np.linalg.norm(x,axis=0)  # column-wis norm

In [ ]:
np.linalg.norm(x,axis=1)  # row-wis norm